const quranSurahs2 = [
  {
    name: "",
    nAyah: 0,
    revelationOrder: 0,
    type: "",
    start: 0,
    end: 0,
    id: 0,
    isAdded: false,
  },
  {
    name: "حمد",
    nAyah: 7,
    revelationOrder: 5,
    type: "meccan",
    start: 1,
    end: 7,
    id: 0,
    isAdded: false,
  },
  {
    name: "بقره",
    nAyah: 286,
    revelationOrder: 87,
    type: "medinan",
    start: 8,
    end: 293,
    id: 0,
    isAdded: false,
  },
  {
    name: "آل عمران",
    nAyah: 200,
    revelationOrder: 89,
    type: "medinan",
    start: 294,
    end: 493,
    id: 0,
    isAdded: false,
  },
  {
    name: "نساء",
    nAyah: 176,
    revelationOrder: 92,
    type: "medinan",
    start: 494,
    end: 669,
    id: 0,
    isAdded: false,
  },
  {
    name: "مائده",
    nAyah: 120,
    revelationOrder: 112,
    type: "medinan",
    start: 670,
    end: 789,
    id: 0,
    isAdded: false,
  },
  {
    name: "انعام",
    nAyah: 165,
    revelationOrder: 55,
    type: "meccan",
    start: 790,
    end: 954,
    id: 0,
    isAdded: false,
  },
  {
    name: "اعراف",
    nAyah: 206,
    revelationOrder: 39,
    type: "meccan",
    start: 955,
    end: 1160,
    id: 0,
    isAdded: false,
  },
  {
    name: "انفال",
    nAyah: 75,
    revelationOrder: 88,
    type: "medinan",
    start: 1161,
    end: 1235,
    id: 0,
    isAdded: false,
  },
  {
    name: "توبه",
    nAyah: 129,
    revelationOrder: 113,
    type: "medinan",
    start: 1236,
    end: 1364,
    id: 0,
    isAdded: false,
  },
  {
    name: "یونس",
    nAyah: 109,
    revelationOrder: 51,
    type: "meccan",
    start: 1365,
    end: 1473,
    id: 0,
    isAdded: false,
  },
  {
    name: "هود",
    nAyah: 123,
    revelationOrder: 52,
    type: "meccan",
    start: 1474,
    end: 1596,
    id: 0,
    isAdded: false,
  },
  {
    name: "يوسف",
    nAyah: 111,
    revelationOrder: 53,
    type: "meccan",
    start: 1597,
    end: 1707,
    id: 0,
    isAdded: false,
  },
  {
    name: "رعد",
    nAyah: 43,
    revelationOrder: 96,
    type: "medinan",
    start: 1708,
    end: 1750,
    id: 0,
    isAdded: false,
  },
  {
    name: "ابراهیم",
    nAyah: 52,
    revelationOrder: 72,
    type: "meccan",
    start: 1751,
    end: 1802,
    id: 0,
    isAdded: false,
  },
  {
    name: "حجر",
    nAyah: 99,
    revelationOrder: 54,
    type: "meccan",
    start: 1803,
    end: 1901,
    id: 0,
    isAdded: false,
  },
  {
    name: "نحل",
    nAyah: 128,
    revelationOrder: 70,
    type: "meccan",
    start: 1902,
    end: 2029,
    id: 0,
    isAdded: false,
  },
  {
    name: "اسراء",
    nAyah: 111,
    revelationOrder: 50,
    type: "meccan",
    start: 2030,
    end: 2140,
    id: 0,
    isAdded: false,
  },
  {
    name: "کهف",
    nAyah: 110,
    revelationOrder: 69,
    type: "meccan",
    start: 2141,
    end: 2250,
    id: 0,
    isAdded: false,
  },
  {
    name: "مریم",
    nAyah: 98,
    revelationOrder: 44,
    type: "meccan",
    start: 2251,
    end: 2348,
    id: 0,
    isAdded: false,
  },
  {
    name: "طاها",
    nAyah: 135,
    revelationOrder: 45,
    type: "meccan",
    start: 2349,
    end: 2483,
    id: 0,
    isAdded: false,
  },
  {
    name: "انبیاء",
    nAyah: 112,
    revelationOrder: 73,
    type: "meccan",
    start: 2484,
    end: 2595,
    id: 0,
    isAdded: false,
  },
  {
    name: "حج",
    nAyah: 78,
    revelationOrder: 103,
    type: "medinan",
    start: 2596,
    end: 2673,
    id: 0,
    isAdded: false,
  },
  {
    name: "مؤمنون",
    nAyah: 118,
    revelationOrder: 74,
    type: "meccan",
    start: 2674,
    end: 2791,
    id: 0,
    isAdded: false,
  },
  {
    name: "نور",
    nAyah: 64,
    revelationOrder: 102,
    type: "medinan",
    start: 2792,
    end: 2855,
    id: 0,
    isAdded: false,
  },
  {
    name: "فرقان",
    nAyah: 77,
    revelationOrder: 42,
    type: "meccan",
    start: 2856,
    end: 2932,
    id: 0,
    isAdded: false,
  },
  {
    name: "شعراء",
    nAyah: 227,
    revelationOrder: 47,
    type: "meccan",
    start: 2933,
    end: 3159,
    id: 0,
    isAdded: false,
  },
  {
    name: "نمل",
    nAyah: 93,
    revelationOrder: 48,
    type: "meccan",
    start: 3160,
    end: 3252,
    id: 0,
    isAdded: false,
  },
  {
    name: "قصص",
    nAyah: 88,
    revelationOrder: 49,
    type: "meccan",
    start: 3253,
    end: 3340,
    id: 0,
    isAdded: false,
  },
  {
    name: "عنکبوت",
    nAyah: 69,
    revelationOrder: 85,
    type: "meccan",
    start: 3341,
    end: 3409,
    id: 0,
    isAdded: false,
  },
  {
    name: "روم",
    nAyah: 60,
    revelationOrder: 84,
    type: "meccan",
    start: 3410,
    end: 3469,
    id: 0,
    isAdded: false,
  },
  {
    name: "لقمان",
    nAyah: 34,
    revelationOrder: 57,
    type: "meccan",
    start: 3470,
    end: 3503,
    id: 0,
    isAdded: false,
  },
  {
    name: "سجده",
    nAyah: 30,
    revelationOrder: 75,
    type: "meccan",
    start: 3504,
    end: 3533,
    id: 0,
    isAdded: false,
  },
  {
    name: "احزاب",
    nAyah: 73,
    revelationOrder: 90,
    type: "medinan",
    start: 3534,
    end: 3606,
    id: 0,
    isAdded: false,
  },
  {
    name: "سباء",
    nAyah: 54,
    revelationOrder: 58,
    type: "meccan",
    start: 3607,
    end: 3660,
    id: 0,
    isAdded: false,
  },
  {
    name: "فاطر",
    nAyah: 45,
    revelationOrder: 43,
    type: "meccan",
    start: 3661,
    end: 3705,
    id: 0,
    isAdded: false,
  },
  {
    name: "یاسین",
    nAyah: 83,
    revelationOrder: 41,
    type: "meccan",
    start: 3706,
    end: 3788,
    id: 0,
    isAdded: false,
  },
  {
    name: "صافات",
    nAyah: 182,
    revelationOrder: 56,
    type: "meccan",
    start: 3789,
    end: 3970,
    id: 0,
    isAdded: false,
  },
  {
    name: "صاد",
    nAyah: 88,
    revelationOrder: 38,
    type: "meccan",
    start: 3971,
    end: 4058,
    id: 0,
    isAdded: false,
  },
  {
    name: "زمر",
    nAyah: 75,
    revelationOrder: 59,
    type: "meccan",
    start: 4059,
    end: 4133,
    id: 0,
    isAdded: false,
  },
  {
    name: "غافر",
    nAyah: 85,
    revelationOrder: 60,
    type: "meccan",
    start: 4134,
    end: 4218,
    id: 0,
    isAdded: false,
  },
  {
    name: "فصّلت",
    nAyah: 54,
    revelationOrder: 61,
    type: "meccan",
    start: 4219,
    end: 4272,
    id: 0,
    isAdded: false,
  },
  {
    name: "شوری",
    nAyah: 53,
    revelationOrder: 62,
    type: "meccan",
    start: 4273,
    end: 4325,
    id: 0,
    isAdded: false,
  },
  {
    name: "زخرف",
    nAyah: 89,
    revelationOrder: 63,
    type: "meccan",
    start: 4326,
    end: 4414,
    id: 0,
    isAdded: false,
  },
  {
    name: "دخان",
    nAyah: 59,
    revelationOrder: 64,
    type: "meccan",
    start: 4415,
    end: 4473,
    id: 0,
    isAdded: false,
  },
  {
    name: "جاثیه",
    nAyah: 37,
    revelationOrder: 65,
    type: "meccan",
    start: 4474,
    end: 4510,
    id: 0,
    isAdded: false,
  },
  {
    name: "احقاف",
    nAyah: 35,
    revelationOrder: 66,
    type: "meccan",
    start: 4511,
    end: 4545,
    id: 0,
    isAdded: false,
  },
  {
    name: "محمد",
    nAyah: 38,
    revelationOrder: 95,
    type: "medinan",
    start: 4546,
    end: 4583,
    id: 0,
    isAdded: false,
  },
  {
    name: "فتح",
    nAyah: 29,
    revelationOrder: 111,
    type: "medinan",
    start: 4584,
    end: 4612,
    id: 0,
    isAdded: false,
  },
  {
    name: "حجرات",
    nAyah: 18,
    revelationOrder: 106,
    type: "medinan",
    start: 4613,
    end: 4630,
    id: 0,
    isAdded: false,
  },
  {
    name: "قاف",
    nAyah: 45,
    revelationOrder: 34,
    type: "meccan",
    start: 4631,
    end: 4675,
    id: 0,
    isAdded: false,
  },
  {
    name: "ذاریات",
    nAyah: 60,
    revelationOrder: 67,
    type: "meccan",
    start: 4676,
    end: 4735,
    id: 0,
    isAdded: false,
  },
  {
    name: "طور",
    nAyah: 49,
    revelationOrder: 76,
    type: "meccan",
    start: 4736,
    end: 4784,
    id: 0,
    isAdded: false,
  },
  {
    name: "نجم",
    nAyah: 62,
    revelationOrder: 23,
    type: "meccan",
    start: 4785,
    end: 4846,
    id: 0,
    isAdded: false,
  },
  {
    name: "قمر",
    nAyah: 55,
    revelationOrder: 37,
    type: "meccan",
    start: 4847,
    end: 4901,
    id: 0,
    isAdded: false,
  },
  {
    name: "الرحمن",
    nAyah: 78,
    revelationOrder: 97,
    type: "medinan",
    start: 4902,
    end: 4979,
    id: 0,
    isAdded: false,
  },
  {
    name: "واقعه",
    nAyah: 96,
    revelationOrder: 46,
    type: "meccan",
    start: 4980,
    end: 5075,
    id: 0,
    isAdded: false,
  },
  {
    name: "حدید",
    nAyah: 29,
    revelationOrder: 94,
    type: "medinan",
    start: 5076,
    end: 5104,
    id: 0,
    isAdded: false,
  },
  {
    name: "مجادله",
    nAyah: 22,
    revelationOrder: 105,
    type: "medinan",
    start: 5105,
    end: 5126,
    id: 0,
    isAdded: false,
  },
  {
    name: "حشر",
    nAyah: 24,
    revelationOrder: 101,
    type: "medinan",
    start: 5127,
    end: 5150,
    id: 0,
    isAdded: false,
  },
  {
    name: "ممتحنه",
    nAyah: 13,
    revelationOrder: 91,
    type: "medinan",
    start: 5151,
    end: 5163,
    id: 0,
    isAdded: false,
  },
  {
    name: "صف",
    nAyah: 14,
    revelationOrder: 109,
    type: "medinan",
    start: 5164,
    end: 5177,
    id: 0,
    isAdded: false,
  },
  {
    name: "جمعه",
    nAyah: 11,
    revelationOrder: 110,
    type: "medinan",
    start: 5178,
    end: 5188,
    id: 0,
    isAdded: false,
  },
  {
    name: "منافقون",
    nAyah: 11,
    revelationOrder: 104,
    type: "medinan",
    start: 5189,
    end: 5199,
    id: 0,
    isAdded: false,
  },
  {
    name: "تغابن",
    nAyah: 18,
    revelationOrder: 108,
    type: "medinan",
    start: 5200,
    end: 5217,
    id: 0,
    isAdded: false,
  },
  {
    name: "طلاق",
    nAyah: 12,
    revelationOrder: 99,
    type: "medinan",
    start: 5218,
    end: 5229,
    id: 0,
    isAdded: false,
  },
  {
    name: "تحریم",
    nAyah: 12,
    revelationOrder: 107,
    type: "medinan",
    start: 5230,
    end: 5241,
    id: 0,
    isAdded: false,
  },
  {
    name: "ملک",
    nAyah: 30,
    revelationOrder: 77,
    type: "meccan",
    start: 5242,
    end: 5271,
    id: 0,
    isAdded: false,
  },
  {
    name: "قلم",
    nAyah: 52,
    revelationOrder: 2,
    type: "meccan",
    start: 5272,
    end: 5323,
    id: 0,
    isAdded: false,
  },
  {
    name: "حاقّه",
    nAyah: 52,
    revelationOrder: 78,
    type: "meccan",
    start: 5324,
    end: 5375,
    id: 0,
    isAdded: false,
  },
  {
    name: "معارج",
    nAyah: 44,
    revelationOrder: 79,
    type: "meccan",
    start: 5376,
    end: 5419,
    id: 0,
    isAdded: false,
  },
  {
    name: "نوح",
    nAyah: 28,
    revelationOrder: 71,
    type: "meccan",
    start: 5420,
    end: 5447,
    id: 0,
    isAdded: false,
  },
  {
    name: "جن",
    nAyah: 28,
    revelationOrder: 40,
    type: "meccan",
    start: 5448,
    end: 5475,
    id: 0,
    isAdded: false,
  },
  {
    name: "مزمل",
    nAyah: 20,
    revelationOrder: 3,
    type: "meccan",
    start: 5476,
    end: 5495,
    id: 0,
    isAdded: false,
  },
  {
    name: "مدثر",
    nAyah: 56,
    revelationOrder: 4,
    type: "meccan",
    start: 5496,
    end: 5551,
    id: 0,
    isAdded: false,
  },
  {
    name: "قیامت",
    nAyah: 40,
    revelationOrder: 31,
    type: "meccan",
    start: 5552,
    end: 5591,
    id: 0,
    isAdded: false,
  },
  {
    name: "انسان",
    nAyah: 31,
    revelationOrder: 98,
    type: "medinan",
    start: 5592,
    end: 5622,
    id: 0,
    isAdded: false,
  },
  {
    name: "مرسلات",
    nAyah: 50,
    revelationOrder: 33,
    type: "meccan",
    start: 5623,
    end: 5672,
    id: 0,
    isAdded: false,
  },
  {
    name: "نباء",
    nAyah: 40,
    revelationOrder: 80,
    type: "meccan",
    start: 5673,
    end: 5712,
    id: 0,
    isAdded: false,
  },
  {
    name: "نازعات",
    nAyah: 46,
    revelationOrder: 81,
    type: "meccan",
    start: 5713,
    end: 5758,
    id: 0,
    isAdded: false,
  },
  {
    name: "عبس",
    nAyah: 42,
    revelationOrder: 24,
    type: "meccan",
    start: 5759,
    end: 5800,
    id: 0,
    isAdded: false,
  },
  {
    name: "تکویر",
    nAyah: 29,
    revelationOrder: 7,
    type: "meccan",
    start: 5801,
    end: 5829,
    id: 0,
    isAdded: false,
  },
  {
    name: "انفطار",
    nAyah: 19,
    revelationOrder: 82,
    type: "meccan",
    start: 5830,
    end: 5848,
    id: 0,
    isAdded: false,
  },
  {
    name: "مطففین",
    nAyah: 36,
    revelationOrder: 86,
    type: "meccan",
    start: 5849,
    end: 5884,
    id: 0,
    isAdded: false,
  },
  {
    name: "انشقاق",
    nAyah: 25,
    revelationOrder: 83,
    type: "meccan",
    start: 5885,
    end: 5909,
    id: 0,
    isAdded: false,
  },
  {
    name: "بروج",
    nAyah: 22,
    revelationOrder: 27,
    type: "meccan",
    start: 5910,
    end: 5931,
    id: 0,
    isAdded: false,
  },
  {
    name: "طارق",
    nAyah: 17,
    revelationOrder: 36,
    type: "meccan",
    start: 5932,
    end: 5948,
    id: 0,
    isAdded: false,
  },
  {
    name: "اعلی",
    nAyah: 19,
    revelationOrder: 8,
    type: "meccan",
    start: 5949,
    end: 5967,
    id: 0,
    isAdded: false,
  },
  {
    name: "غاشیه",
    nAyah: 26,
    revelationOrder: 68,
    type: "meccan",
    start: 5968,
    end: 5993,
    id: 0,
    isAdded: false,
  },
  {
    name: "فجر",
    nAyah: 30,
    revelationOrder: 10,
    type: "meccan",
    start: 5994,
    end: 6023,
    id: 0,
    isAdded: false,
  },
  {
    name: "بلد",
    nAyah: 20,
    revelationOrder: 35,
    type: "meccan",
    start: 6024,
    end: 6043,
    id: 0,
    isAdded: false,
  },
  {
    name: "شمس",
    nAyah: 15,
    revelationOrder: 26,
    type: "meccan",
    start: 6044,
    end: 6058,
    id: 0,
    isAdded: false,
  },
  {
    name: "لیل",
    nAyah: 21,
    revelationOrder: 9,
    type: "meccan",
    start: 6059,
    end: 6079,
    id: 0,
    isAdded: false,
  },
  {
    name: "ضحی",
    nAyah: 11,
    revelationOrder: 11,
    type: "meccan",
    start: 6080,
    end: 6090,
    id: 0,
    isAdded: false,
  },
  {
    name: "شرح",
    nAyah: 8,
    revelationOrder: 12,
    type: "meccan",
    start: 6091,
    end: 6098,
    id: 0,
    isAdded: false,
  },
  {
    name: "تین",
    nAyah: 8,
    revelationOrder: 28,
    type: "meccan",
    start: 6099,
    end: 6106,
    id: 0,
    isAdded: false,
  },
  {
    name: "علق",
    nAyah: 19,
    revelationOrder: 1,
    type: "meccan",
    start: 6107,
    end: 6125,
    id: 0,
    isAdded: false,
  },
  {
    name: "قدر",
    nAyah: 5,
    revelationOrder: 25,
    type: "meccan",
    start: 6126,
    end: 6130,
    id: 0,
    isAdded: false,
  },
  {
    name: "بینه",
    nAyah: 8,
    revelationOrder: 100,
    type: "medinan",
    start: 6131,
    end: 6138,
    id: 0,
    isAdded: false,
  },
  {
    name: "زلزله",
    nAyah: 8,
    revelationOrder: 93,
    type: "medinan",
    start: 6139,
    end: 6146,
    id: 0,
    isAdded: false,
  },
  {
    name: "عادیات",
    nAyah: 11,
    revelationOrder: 14,
    type: "meccan",
    start: 6147,
    end: 6157,
    id: 0,
    isAdded: false,
  },
  {
    name: "قارعه",
    nAyah: 11,
    revelationOrder: 30,
    type: "meccan",
    start: 6158,
    end: 6168,
    id: 0,
    isAdded: false,
  },
  {
    name: "تکاثر",
    nAyah: 8,
    revelationOrder: 16,
    type: "meccan",
    start: 6169,
    end: 6176,
    id: 0,
    isAdded: false,
  },
  {
    name: "عصر",
    nAyah: 3,
    revelationOrder: 13,
    type: "meccan",
    start: 6177,
    end: 6179,
    id: 0,
    isAdded: false,
  },
  {
    name: "همزه",
    nAyah: 9,
    revelationOrder: 32,
    type: "meccan",
    start: 6180,
    end: 6188,
    id: 0,
    isAdded: false,
  },
  {
    name: "فیل",
    nAyah: 5,
    revelationOrder: 19,
    type: "meccan",
    start: 6189,
    end: 6193,
    id: 0,
    isAdded: false,
  },
  {
    name: "قریش",
    nAyah: 4,
    revelationOrder: 29,
    type: "meccan",
    start: 6194,
    end: 6197,
    id: 0,
    isAdded: false,
  },
  {
    name: "ماعون",
    nAyah: 7,
    revelationOrder: 17,
    type: "meccan",
    start: 6198,
    end: 6204,
    id: 0,
    isAdded: false,
  },
  {
    name: "کوثر",
    nAyah: 3,
    revelationOrder: 15,
    type: "meccan",
    start: 6205,
    end: 6207,
    id: 0,
    isAdded: false,
  },
  {
    name: "کافرون",
    nAyah: 6,
    revelationOrder: 18,
    type: "meccan",
    start: 6208,
    end: 6213,
    id: 0,
    isAdded: false,
  },
  {
    name: "نصر",
    nAyah: 3,
    revelationOrder: 114,
    type: "medinan",
    start: 6214,
    end: 6216,
    id: 0,
    isAdded: false,
  },
  {
    name: "مسد",
    altName: "المسد",
    nAyah: 5,
    revelationOrder: 6,
    type: "meccan",
    start: 6217,
    end: 6221,
    id: 0,
    isAdded: false,
  },
  {
    name: "اخلاص",
    nAyah: 4,
    revelationOrder: 22,
    type: "meccan",
    start: 6222,
    end: 6225,
    id: 0,
    isAdded: false,
  },
  {
    name: "فلق",
    nAyah: 5,
    revelationOrder: 20,
    type: "meccan",
    start: 6226,
    end: 6230,
    id: 0,
    isAdded: false,
  },
  {
    name: "ناس",
    nAyah: 6,
    revelationOrder: 21,
    type: "meccan",
    start: 6231,
    end: 6236,
    id: 0,
    isAdded: false,
  },
];

quranSurahs2.forEach((surah, index) => {
  surah.id = index;
});

export default quranSurahs2;
